---
title: "R심화_3월 12일"
author: "Seongtaek"
date: "2024-03-12"
output:
  prettydoc::html_pretty:
    theme: cayman
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  comment = "#>",
  collapse = TRUE # Code와 Output을 분리시키지 않고 하나로 출력시켜 줌
  )
```

## 라이브러리 로드
- hflights (항공 데이터셋)
- 설치: install.packages()
- 모든 변수제거: rm(list = ls())

```{r,warning=FALSE,message=FALSE}
library(hflights)
```

```{r}
# 차원 파악
dim(hflights)

# 새로운 변수명으로 저장
hflights2 <- hflights

# 데이터셋 로드
head(hflights2) 

# View 형식으로 로드
View(hflights2)

# class 확인
class(hflights2)

# 속성 확인
str(hflights2)
```

## 라이브러리 로드
- dplyr

```{r,warning=FALSE,message=FALSE}
library(dplyr)
```

### dplyr 패키지의 다양한 기능들

```{r}
# 1월 10일 데이터 출력
temp_jan10 <- filter(hflights2, Month==1, DayofMonth==10)
temp_jan10 %>% head()

# 2011년 2월4일 휴스턴공항(IAH) 발 AA항공사의 운행기록 추출
AA_20110204 <- hflights %>% filter(Month==2, DayofMonth==4, UniqueCarrier=="AA")
AA_20110204
AA_20110204 %>% dim()

# 2011년 3월, 5월에 휴스턴공항(IAH)을 이륙한 UA항공사의 운행기록 추출
UA_201103_201105 <- hflights2 %>% filter(Month==3|Month==5, UniqueCarrier=="UA")
UA_201103_201105 %>% head()
UA_201103_201105 %>% dim()

# 2011년에 도착지연시간(ArrDelay)이 100분 이상인 운행 기록을 추출하세요. 몇건인가요?
ArrDelay <- hflights2 %>% filter(ArrDelay >= 100)
ArrDelay %>% head()
ArrDelay %>% dim()

# 예제) 2011년에 AA 항공사의 도착지연시간(ArrDelay)이 100분 이상인 운행기록을 추출하세요. 몇건인가요?
AA_ArrDelay <- hflights2 %>% filter(ArrDelay >= 100,UniqueCarrier=="AA")
AA_ArrDelay %>% head()
AA_ArrDelay %>% dim()

### 인덱싱
# 열이름이 UniqueCarrier 인 열 추출
hflights2$UniqueCarrier %>% head()

# 7번째 열(UniqueCarrier열) 추출
hflights2[,7] %>% head()

### 월 추출 간단한방법
hflights2 %>% filter(hflights2$Month==5) %>% head()
hflights2 %>% filter(hflights2$Month==5) %>% dim()
```



